version: '3.8'

services:
  frontend:
    build: 
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
